In [3]:
from training.models import SphereConfidenceFace
import torch

In [6]:
model = SphereConfidenceFace.load_from_checkpoint(
    checkpoint_path="/app/outputs/scf_train/weights_scf_psd/epoch=4-step=113000.ckpt",
)

TypeError: __init__() missing 7 required positional arguments: 'backbone', 'head', 'scf_loss', 'softmax_weights', 'optimizer_params', 'scheduler_params', and 'permute_batch'

In [15]:
import torch

torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [13]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
labels = np.array([0, 1, 0, 2])

In [14]:
A[np.arange(4), labels]

array([ 1,  5,  7, 12])

In [7]:
A[labels]

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])